### ISSUE TITLE
尝试调试运行失败

### ISSUE THREAD

**Issue by daofeng2015** [qydysky/bili_danmu#41]
![QQ截图20210125030553](https://user-images.githubusercontent.com/14891398/105640711-58b33680-5eba-11eb-8f3f-c01a93f66af6.png)
说是这个依赖找不到.能否解决下

**Comment by daofeng2015** [comment]
![QQ截图20210125030821](https://user-images.githubusercontent.com/14891398/105640756-99ab4b00-5eba-11eb-9326-abb729971bcd.png)
日志依赖也提升同步失败

**Comment by qydysky** [comment]
在 0adad1a602a24132b9facf3d86525a42a9fa75f5 修复

**Comment by daofeng2015** [comment]
![QQ截图20210125203716](https://user-images.githubusercontent.com/14891398/105706958-2e5e8900-5f4d-11eb-9ab0-c838df8eae29.png)
还有个依赖没更新

**Comment by qydysky** [comment]
在 8023b7cff7976aab08a22833ce6c6fa2a00bf61f 修复
