### ISSUE TITLE
linux下如何使用GTK GUI

### ISSUE THREAD

**Issue by GoMapur** [qydysky/bili_danmu#58]
Hi, 请问linux下如何运行截图所示窗口： https://github.com/qydysky/bili_danmu/blob/maintenance/_Screenshot/2020-12-12_16-43-09.gif

**Comment by qydysky** [comment]
sry，现在才发现没有watch自己的项目。
经过虚拟机测试
在ubuntu20.04中，安装libgtk-3-dev gcc
并且在config_K_v.json中将`Gtk弹幕窗`置为true
clone项目后，在demo中运行go run -tags "gtk" main.go即可，第一次可能要较长时间编译


![Snipaste_2022-04-10_22-38-46](https://user-images.githubusercontent.com/32743305/162624861-22a36e53-8fa6-4e9f-92e9-61e51dc76d15.png)

**Comment by GoMapur** [comment]
> sry，现在才发现没有watch自己的项目。 经过虚拟机测试 在ubuntu20.04中，安装libgtk-3-dev gcc 并且在config_K_v.json中将`Gtk弹幕窗`置为true clone项目后，在demo中运行go run -tags "gtk" main.go即可，第一次可能要较长时间编译
> 
> ![Snipaste_2022-04-10_22-38-46](https://user-images.githubusercontent.com/32743305/162624861-22a36e53-8fa6-4e9f-92e9-61e51dc76d15.png)

谢谢！

**Comment by GoMapur** [comment]
谢谢！
